SELECT * FROM LOCATIONS NATURAL JOIN COUNTRIES;

SELECT * FROM LOCATIONS JOIN COUNTRIES USING (COUNTRY_ID);

SELECT * FROM LOCATIONS L JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;

SELECT * FROM LOCATIONS L INNER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;

SELECT * FROM LOCATIONS L LEFT JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;

SELECT * FROM LOCATIONS L RIGHT JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;

SELECT * FROM LOCATIONS L FULL OUTER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;