SELECT * FROM JOBS NATURAL JOIN JOB_HISTORY;

SELECT * FROM JOBS JOIN JOB_HISTORY USING (JOB_ID);

SELECT * FROM JOBS J JOIN JOB_HISTORY JH ON J.JOB_ID = JH.JOB_ID;

SELECT * FROM JOBS J INNER JOIN JOB_HISTORY JH ON J.JOB_ID = JH.JOB_ID;

SELECT * FROM JOBS J LEFT JOIN JOB_HISTORY JH ON J.JOB_ID = JH.JOB_ID;

SELECT * FROM JOBS J RIGHT JOIN JOB_HISTORY JH ON J.JOB_ID = JH.JOB_ID;

SELECT * FROM JOBS J FULL OUTER JOIN JOB_HISTORY JH ON J.JOB_ID = JH.JOB_ID;

